project:
  type: website

website:
  title: "Hirotaka Fukui"
  twitter-card: 
    site: "@PittiKing"
    creator: "@PittiKing"
  image: static\HIROTAKA FUKUI.png
  favicon: static\HIROTAKA FUKUI.png
  site-url: https://fukui-hirotaka.com/
 

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    smooth-scroll: true
    include-in-header:
      text: |
        <meta name="robots" content="noindex">




