project:
  type: website

website:
  title: "Hirotaka Fukui"
  site-url: https://fukui-hirotaka.com/
  description: "Doctoral student in Economics. Research on international macroeconomics, monetary economics, macro-finance."
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: notes.qmd
        text: Notes
    right:
      - icon: github
        href: https://github.com/Hirotaka-Fukui-Pitti-King
      - icon: envelope
        href: mailto:227e127e@gsuite.kobe-u.ac.jp
      - icon: twitter-x
        href: https://x.com/PittiKing
      - icon: instagram
        href: https://www.instagram.com/pegutti_king/
      - icon: substack
        href: https://substack.com/@pittiking
      - icon: linkedin
        href: https://www.linkedin.com/in/hirotaka-fukui-90495b342
      - text: "ORCID"
        href: https://orcid.org/{{< var orcid >}}

  page-footer:
    right: |
      <i class="bi bi-c-circle"></i> 2025 Hirotaka Fukui. </span>

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    smooth-scroll: true




