---
title: "CV"
author:
  - name: Hirotaka Fukui
    email: 227e127e@gsuite.kobe-u.ac.jp
date-modified: last-modified
---

# Hirotaka Fukui  
Ph.D. Student in Economics, Kobe University  

## Current Position
**Ph.D. Student**, Graduate School of Economics, Kobe University, Apr. 2024 - present  

- Advisors: Shigeto Kitano, Yoichi Matsubayashi, 
- Fields: International Macroeconomics, Monetary Economics, Macro-Finance

## Education

M.A. in Economics, Kobe University, Japan, 2024.

B.A. in Language and Area Studies (Africa), Tokyo University of Foreign Studies, Japan, 2022.

## Working Papers
- [**The Effects of Financial Liberalization on Sovereign Risk: A Continuous-Time Model of Sovereign Debt under Capital-Account Openness**](https://mpra.ub.uni-muenchen.de/id/eprint/127909) MPRA Paper 127909.

- [**On the Sources of Macroeconomic Fluctuations in Sub-Saharan African Countries**](https://mpra.ub.uni-muenchen.de/id/eprint/127916) MPRA Paper 127916.

*(Under preparation)*

- **Business cycle fluctuations in Sub-Saharan African macroeconomic time series**

- **Trade shocks and macroeconomic fluctuations in Africa. A Replication Study of Kose and Riezman (Journal of Development Economics, 2001)**

- **High Volatility in Consumption for Africa: Role of Food Import Dependence**

- **Aggregate Fluctuations in Sub-Saharan African Economies: The role of Informality**

- **Exporting Crude, Importing Petroleum: The Sources of Volatility in African Oil Producers**

- **Natural Disasters and High Volatility in Consumption in Low-Income Countries**
  
## Teaching Experience

**Teaching Assistant**, Kobe University  

- *Advanced Macroeconomics I* (Ph.D., Prof. Tetsugen Haruyama), 2024 Q3  
- *Econometrics* (Undergraduate, Prof. Yoichi Matsubayashi), Spring 2024, 2025  
- *Intermediate Macroeconomics* (Undergraduate, Profs. Tetsugen Haruyama & Agata Wierzbowska), Spring 2025  
- *Economic Statistics* (Undergraduate, Prof. Yoichi Matsubayashi), Fall 2024, 2025  
- *Programming & Economic Analysis* (Undergraduate, Prof. Tetsugen Haruyama), Fall 2024
- *Advanced Macroeconomics I* (Ph.D., Prof. Kazuharu Yanagimoto), 4Q 2025
- *Advanced Macroeconomics IV* (Ph.D., Prof. Kazuharu Yanagimoto), Fall 2025


## Presentations & Seminars (* Scheduled)
2025:  [Economics Workshop for Young Economists](https://sites.google.com/site/kansaimacro/), Monetary Economics Seminar of Kobe University, Spring Conference of the Japan Society of International Economics, 2025 Princeton Initiative (**Selected participant**), JSIE Next Generation Workshop, 20th Macroeconomics Conference for Young Economists* 


## Fellowships and Awards
- JST SPRING Fellowship, JST, 2024–present
- Prioritized Research Funds, Kobe University, 2025.
- Grant for Publication of Research Results, Kobe University, 2025.


## Other Activities

- Completed, [IMF 19th Macroeconomist Training Program, IMF Regional Office for Asia and the Pacific in cooperation with JICA, 2024](https://www.imf.org/-/media/files/oap/oap-home/2023/19th-mtp-flyer-agenda-final.pdf)  
- Completed, [KOBE HPC Summer School, cosponsored by Kobe University, University of Hyogo, and RIKEN Center for Computational Science (R-CCS), 2024](https://www.eccse.kobe-u.ac.jp/simulation_school/kobe-hpc-summer-basic-2024/)
- Selected participant, [2025 Princeton Initiative, Princeton University, Bendheim Center for Finance, 2025](https://initiative.princeton.edu/programs/2025-program/) 
- Completed, [2025 Macrofinance Online Summer School, Princeton University, Bendheim Center for Finance, 2025](https://initiative.princeton.edu/2025-macrofinance-online-summer-school/)

## Programming and Skills

- Languages: Japanese, English, French
- Programming: MATLAB, Julia, Python, R, Fortran, C, Stata

## Professional Memberships
- Japan Society of International Economics  
- Japanese Economic Association
- Japan Society of Monetary Economics

## Service
- Chair of the Executive Committee, The Student Council of the Graduate School of Economics, Kobe U, Apr. 2024-Mar. 2025
