---
title: "Research"
description: "Research projects and papers"
body-classes: research-page
format:
  html:
    toc: true
    toc-location: left                                 
---

# Research Agenda

# Sub-Saharan Africa

## Working Papers

- [**On the Sources of Macroeconomic Fluctuations in Sub-Saharan African Countries**](research/lively-llama.qmd) [MPRA Paper 127916](https://mpra.ub.uni-muenchen.de/id/eprint/127916).

- **Real Business Cycles in Sub-Saharan Africa: Stylized Facts and Comparative Evidence through the Lens of Financial Frictions**

## Publications

## Work in Progress

- **Trade shocks and macroeconomic fluctuations in Africa. A Replication Study of Kose and Riezman (Journal of Development Economics, 2001)**

- **Investment Specific Technology Shocks and Real Business Cycles in Sub-Saharan African Economies**

- **High Volatility in Sub-Saharan African Macroeconomic Fluctuations: Role of Staple Food Import Dependence**

- **Import Price Shocks and High Volatility in Consumption of Sub-Saharan African Countries**

- **Aggregate Fluctuations in Sub-Saharan African Economies: The role of Informality**

- **Exporting Crude, Importing Petroleum: The Sources of Volatility in African Oil Producers**

- **Explaining business cycles in Sub-Saharan African economies: How much do commodity prices matter?**

- **Natural Disasters and High Volatility in Consumption in Low-Income Countries**

- **Import Price Shocks and High Volatility in Consumption of Sub-Saharan African Countries**

- **Explaining business cycles in Sub-Saharan African economies: ‘How much do world prices matter?’**

- **Quantitative Analysis of Ghana's 2014-2016 Macroeconomic Crisis**

- **Rollover Risk and Sovereign Credit Ratings: The Debt Burden Channel in Low-income Countries**

- **Global Financial Conditions, Trade Finance, and Real Business Cycles in Sub-Saharan Africa**

- **Trade Dynamics and Real Business Cycles in Sub-Saharan African Economies**

- **Sovereign Risk, Leverage, and Business Cycles in Sub-Saharan African Economies**

- **Banking Crises and Government Financial Policy in Sub-Saharan Africa: A Quantitative Perspective**

- **How Important Are Trade Shocks for Macroeconomic Fluctuations in Africa?**

- **Adjustment cost, Irreversibility, and Uncertainty in Investment: Cause of Volatility in Sub-Saharan African Economies**

- **Why doesn’t Capital Flow to African Countries?**

- **Dynamic Irreversible Militarization Process Experience from Zimbabwe**

- **Political Cause of Hyperinflation: Evidence from Zimbabwe**

- **Monetary Resilience after Hyperinflation in Zimbabwe: Dollarization, De-dollarization, and the Role of Credibility**

- **Was Robert Mugabe Truly a Ruthless Dictator?**

# Macro-Finance

## Working Papers

## Publications

## Work in Progress

- **How Financial Frictions Constrain Fiscal Space in Emerging Economies?**

# Others

## Working Papers

## Publications

## Work in Progress

- **Commodity Booms and Busts are Not All Alike in Emerging Economies**

- **Rent Seeking, Tariff Evasion, and Inflation**

# Permanent working papers

- **Business cycle fluctuations in Sub-Saharan African macroeconomic time series**

- **MXN-Trend Model**