---
title: To Heart
engine: julia
format:
  html:
    code-tools: true
---

::: {.callout-important}
All rights reserved. All errors in this document are the responsibility of the author. 
Although every effort has been made to ensure the accuracy of this material, I cannot guarantee that it is free of errors or misprints. 
Use at your own risk. 
If you find any errors, please get in touch with me.
:::

# General Equilibrium Theory

> “The two central problems of the theory that this monograph presents are (1) the explanation of the prices of commodities resulting from the interaction of the agents of a private ownership economy through markets, (2) the explanation of the role of prices in an optimal state of an economy. The analysis is therefore organized around the concept of a price system or, more generally, of a value function defined on the commodity space.”  
> — Gérard Debreu, *The Theory of Value* 

Now, let us view a competitive economy from the general equilibrium perspective.
As Debreu (1959) emphasizes, general equilibrium theory seeks to explain how the prices of commodities emerge from the interactions of agents in a market economy, and how those prices, in turn, sustain an optimal allocation of resources.

Consider an economy with $H$ commodities indexed by $h \in \mathcal{H} = {1, \dots, H}$, $I$ consumers indexed by $i \in \mathcal{I} = {1, \dots, I}$, and $J$ producers or firms indexed by $j \in \mathcal{J} = {1, \dots, J}$.

Consumers derive utility from consuming goods. Let $X$ denote the **consumption correspondence**, which maps each consumer $i \in \mathcal{I}$ to a subset $X(i) = X_i \subseteq \mathbb{R}^{\mathcal{H}}$ of the commodity space, representing the set of consumption bundles available to that consumer.
Each element $x_i \in X_i$ is a **consumption bundle** (or consumption vector), describing quantities of all commodities that the consumer may feasibly consume.

Let $R$ be a **preference correspondence** that maps each $i \in \mathcal{I}$ to a reflexive binary relation $R(i) = R_i \subseteq X_i \times X_i$ over $X_i$, representing the consumer’s preference ordering such that $(x_i, x_i) \in R_i$ for all $x_i \in X_i$.

Each producer $j \in \mathcal{J}$ operates a **production set** $Y(j) = Y_j \subseteq \mathbb{R}^{\mathcal{H}}$, where each element $y_j \in Y_j$ is a **production bundle** (or production vector) describing quantities of inputs and outputs across commodities.

The total resources available in the economy are represented by an **aggregate endowment vector** $\bar{\omega} \in \mathbb{R}^{\mathcal{H}}$, where $\bar{\omega} = (\bar{\omega}(h))_{h \in \mathcal{H}} = (\bar{\omega}h)_{h \in \mathcal{H}}$ specifies the total amount of each commodity in the economy, not necessarily individualized among agents.
These commodities are assumed to be pre-existing and dated. It means that each good has a defined origin in time.

::: {#def-econ}

## Economy

The list $(\mathcal{H}, \mathcal{I}, \mathcal{J}, X, R, Y, \bar{\omega})$ is an economy if

1. $\mathcal{H}$ is a nonempty finite set of commodities;
1. $\mathcal{I}$ is a nonempty finite set of consumers;
1. $\mathcal{J}$ is a nonempty finite set of producers or firms;
1. $X$ is a correspondence from $\mathcal{I}$ to the commodity space $\mathbb{R}^{\mathcal{H}}$;
1. $R$ is a correspondence from $\mathcal{I}$ to $\mathbb{R}^{\mathcal{H}} \times \mathbb{R}^{\mathcal{H}}$ such that $R(i)$ is a reflexive binary relation over $X_{i}$ s.t. $(x_{i},x_{i}) \in R_{i}$ for each $x_{i} \in X_{i}$;
1. $Y$ is a correspondence from $\mathcal{J}$ to $\mathbb{R}^{\mathcal{H}}$; and
1. $\bar{\omega}$ is a point of $\mathbb{R}^{\mathcal{H}}$.
:::

::: {#def-FeaAlo}

## Feasible Allocation

Let $(\mathcal{H}, \mathcal{I}, \mathcal{J}, X, R, Y, \bar{\omega})$ be an economy. Then $(x, y) \in (\mathbb{R}^{\mathcal{H}})^{\mathcal{I}} \times (\mathbb{R}^{\mathcal{H}})^{\mathcal{J}}$ is a feasible allocation for $(\mathcal{H}, \mathcal{I}, \mathcal{J}, X, R, Y, \bar{\omega})$ if $(x, y) \in X \times Y$ and $\sum_{i \in \mathcal{I}}x_{i}=\bar{\omega}+\sum_{j \in \mathcal{J}}y_{i}$.

:::
