---
title: "Close To You"
engine: julia
format:
  html:
    code-tools: true
---

> The moment I see you,
> Time will stop.
> All of the light of the world will only shine on us.
> I’m gonna fly above the clouds.
> [*Close To You* - fromis_9](https://fromis9.fandom.com/wiki/Close_To_You)

# Answer to the Ultimate Question of Life, the Universe, and Everything

To understand why some societies prosper while others remain poor is among the oldest questions in economics. At the center of this inquiry lies the theory of economic growth.

From the basic facts of income and development, we trace a path toward formal representations of economic dynamics, built upon the tools of optimal control and dynamic programming. Along this path, the neoclassical growth model gives way to frameworks that incorporate human capital, innovation, and endogenous technological change. Special attention is paid to directed technical change and to the interaction between competition, market structure, and growth.

We then turn to the forces that shape economic performance across time and space: finance, trade, and institutions. By combining theory with evidence, we seek to uncover the mechanisms through which technological progress emerges and enduring differences in prosperity take root.

The aim is not only to construct models, but to develop an intuition for the deep forces that drive long-run growth and structural change.

## Technological Progress

With headlines about breakthroughs in artificial intelligence, quantum computing, and biotechnology, we often lose sight of the fundamental question. What do we talk about when we talk about technological progress? The answer is far more complex than simply referring to faster computers and more efficient machines.

When discussing technological advances, we tend to gravitate toward metrics that are easy to measure. For example, processing power doubles every two years, or battery capacity increases at a particular rate. Such metrics may create the comfortable illusion of linear progress, but they are only part of the story.

Consider the smartphone in your pocket. Is it "better" than the one before it because it has more computing power or because it enables new forms of human connection? The public discourse on technological progress may focus on the former, but the latter will undoubtedly mean more meaningful progress. 

Technological progress is a simultaneous process with multiple dimensions. For example, technological advancement will increase the power and efficiency of its tools. However, society must also evaluate technological progress regarding how widely such improvements will be available, how seamlessly they will integrate into society, how well they will reinforce inherent human capabilities, and how sustainable they will be. 

Technological progress in one dimension often comes at the expense of another. A given new technology may offer us tremendous capabilities, but at the same time, it may cause major environmental problems. Perhaps the greatest irony in discussing technological progress is the tendency to conflate capabilities with benefits. The assumption that more powerful technology will automatically lead to better outcomes for humanity is often challenged. 

Take social media, for example. By any technical measure --- speed, reach, ability to engage, etc. --- recent social networking sites have made tremendous strides compared to previous communication technologies. However, its impact on mental health, social cohesion, and democratic discourse is still hotly debated. This is not to suggest that social media is a setback rather than progress, but that technological progress itself is more complex than we often realize.

How has technological progress been discussed in the theory of economic growth in macroeconomics, the subject of this note? The cornerstone of economic growth theory, Solow's growth model, treats technological progress as an exogenous factor, a force outside the economic system to increase productivity. In Solow's framework, long-term growth is determined entirely by technological progress and population growth, and the famous "Solow's residual" would represent the portion of growth that conventional capital and labor inputs cannot explain. 

While this model helped explain the growth patterns of the West and other developed countries after WWII, its limitations became increasingly apparent. Solow's growth model failed to explain why some countries innovate faster than others, how technological progress occurs, and why the convergence between rich and poor countries does not materialize as predicted. Most importantly, it treated technological progress, the driving force of growth, as a black box. 

The limitations of the Solow model led to the development of endogenous growth theory, which attempts to look inside the black box of technological progress. It suggested that capital accumulation (broadly speaking, including both physical and human capital) could lead to sustained growth without diminishing returns, thus taking the first important step in the story of technological progress. This reversed the Solow model's prediction that growth would eventually plateau without exogenous technological progress. 

Paul Romer furthered his contribution by modeling technological progress as an intentional outcome of R\&D activities. In Romer's framework, blueprints of technology are non-competitive (can be used by multiple people simultaneously) but partially excludable (through patents and intellectual property rights), creating a unique economic dynamic. This insight is based on several essential features of modern technological progress: the effect of scale, where larger markets support more innovation because ideas are available at any scale; path dependence, where today's technological possibilities depend on past discoveries, and innovation in one field, spillover effects, in which innovations in one field often bring unexpected benefits to other fields. 

Later, endogenous growth theory was refined, especially by Philippe Aghion and Peter Howitt, to emphasize the role of the famous "creative destruction" concept once advocated by Schumpeter. Their Schumpeterian growth model suggested that the pace of innovation depends heavily on factors such as the quality of the educational system (human capital development), market structure and competition policy, intellectual property rights, financial system development, and political institutions. They showed that investment in R &D alone could not translate technological potential into actual progress; complementary institutions and policies are needed. 

The concept of "Directed Technical Change," proposed by Daron Acemoglu, was a decisive advance in our understanding of technological progress. Unlike previous models that treated technological change as neutral, Acemoglu's framework shows how market forces and economic incentives guide the direction of technological innovation. As technology becomes more pervasive, it will make it easier for highly skilled people to use their abilities to increase their incomes. In contrast, less experienced people may lose their jobs as computers take over their careers. In an era where AI technology is expected to become more and more advanced, it is crucial to understand how technology is increasingly necessary to think about how it will affect employment and whether it will continue to do so. The concept of "Directed Technical Change," proposed by Daron Acemoglu, provides a clue to these questions.

When we talk about technological progress, we are talking about the source of progress for human society. It is about our ability to create tools that enhance our capabilities while aligning with our values and supporting the prosperity of human civilization and the natural world. This unusual and nuanced understanding of technological progress does not diminish its importance but can place it in its proper context as a component of human development. 

Contemporary theories of economic growth have evolved to recognize and incorporate the complex interplay between technology, institutions, and human capital. Similarly, our discourse on technological progress must evolve beyond simplistic arguments to a more holistic understanding of what it truly means. To do so, we need to expand our vocabulary around technological progress rather than abandoning measurement or becoming technological pessimists. 

This means developing new measures that capture human well-being, social cohesion, and environmental sustainability alongside traditional measures of technological capability. And it also means acknowledging that progress is not always linear or universally beneficial. Sometimes, we may have to choose not to adopt certain technologies or to deliberately limit their scope to preserve other values we hold dear. In the future, when we come across headlines about technological advances, perhaps we should ask "how much faster/better/stronger" and "for what/who/at what cost" the advances were made. That question will help shape the technological progress our society deserves to have, and endogenous economic growth theory can help us think about such questions.

### Creative Destruction: What does innovation bring to an economy?

In the traditional model of expansionary product diversification (e.g., Romer 1990), adding new products was considered the source of technological progress. In reality, however, most technological innovation is "improving the quality of existing products (vertical innovation)". Such innovation leads to growth by displacing old products (creative destruction) and taking market share (Aghion and Howitt 1992).

In the model, time is continuous. The economy has four agents: households, the final goods sector, the intermediate goods sector, and the R&D sector.

Each intermediate good (machine) is defined in the interval of $\nu \in [0,1]$, and quality is modeled as follows:

$$
    q(\nu, t) = \lambda^{n(\nu, t)}q(\nu, 0),~\lambda>1
$$

Where $q(\nu, t)$ is the quality of the machine line $\nu$ and $n(\nu, t)$ is the number of innovations that have occurred up to that point. The quality of the machine line is multiplied by $\lambda$ for each increase in quality. This implies a ladder-like quality improvement.

In this model, households are primarily: consumers of goods (obtaining utility through consumption), labor providers (supplying labor to the final goods sector and the R&D sector), and asset holders (receiving profits from R\&D firms, etc.). The economy in this model is assumed to have representative households that live indefinitely. Households maximize their utility 

$$
    U = \int_{t=0}^{\infty} e^{-\rho t} \frac{C(t)^{1-\theta}-1}{1-\theta} dt, ~\theta>0
$$

subject to their budget constraint

$$
    \dot{A}(t) = r(t)A(t)+w(t)L-C(t)
$$

where $C(t)$ is consumption at time $t$, $A(t)$ is the household's asset holdings, $r(t)$ is the return on assets, $w(t)$ is the wage rate, and $L$ is the labor supply (assumed constant).

The Hamiltonian for the utility maximization problem of the household is set up as follows:

$$
\mathcal{H}=e^{-\rho t}\frac{C_{t}^{1-\theta}-1}{1-\theta}+\mu(t)\bigl[r(t)A(t)+w(t)L-C(t)\bigr]
$$

Where $\mu(t)$ is the costate variable associated with the household's asset accumulation.

The first-order conditions for optimization are as follows:

$$
\begin{align}
    e^{-\rho t}C(t)^{-\theta} & =\mu_{t} \\
    \dot{\mu}(t)+r(t)\mu(t) & =0 
\end{align}
$$

The first condition indicates that the marginal utility of consumption equals the shadow price of wealth, while the second condition describes the evolution of the shadow price over time.

The Euler equation governing the optimal consumption path is derived from the first-order condition of the household's intertemporal optimization problem. Taking the logarithm of both sides of the equation, we get:

$$
-\rho t-\theta \ln C(t) = \ln \mu(t)
$$

Differentiating both sides of equation concerning time $t$, we obtain:

$$
-\rho-\theta \frac{\dot{C}(t)}{C(t)}=\frac{\dot{\mu}(t)}{\mu(t)}
$$

From the first order condition, $\frac{\dot{\mu}(t)}{\mu(t)}=-r(t)$. Therefore, we get the Euler equation by substituting this.

$$
\frac{\dot{C}(t)}{C(t)} = \frac{r(t)-\rho}{\theta}
$$

::: {.callout-important}
All rights reserved. All errors in this document are the responsibility of the author. 
Although every effort has been made to ensure the accuracy of this material, I cannot guarantee that it is free of errors or misprints. 
Use at your own risk. 
If you find any errors, please get in touch with me.
:::