---
title: Clover
format:
  html:
    code-tools: true
    number-sections: true
---

> 꿈꾸던 날을 기다려
> 
> 앞만 보고서 내달려
> 
> 놓치고 있던 게 너무나 많아
>
> 행운을 바랬어
> 
> 바보라 몰랐어
> 
> 내가 바래왔던 건 행복인데
> 
> [***Clover*** - fromis_9](https://fromis9.fandom.com/wiki/Clover)

***Numerical Method for Macroeconomics***

# なぜマクロ経済学で数値解法が必要になるのか

DSGEモデルは現代マクロ経済理論を用いて景気循環における集計時系列の共変動を説明·予測するモデルです。DSGEモデルでは経済主体の意思決定ルールが選好·技術·情報·財政金融政策レジームに関する仮定から異時点間最適化問題を解くことによって導かれます。この性質によりDSGEモデルは理論的一貫性を持つ経験モデルとなり、政策実験の実験室として有用なものとなります。したがって、DSGEモデルの中心にはpreferences, technologies, information, policy regimeという構造があり、intertemporal optimization problemsを解き、decision rulesを得るという流れになります。

DSGEモデルは例外的な少数のケースを除いて、均衡動学の閉形式解を「紙と鉛筆」で導くことが困難です。そのため、コンピュータと数値的方法を用いて近似解を求める必要があります。ここでいう「解く」とは、たとえば資本 $k_t$ 、消費 $c_t 、生産性 $z_t$ が与えられたときに、次期資本 $k_{t+1}$  や消費 $c_{t+1}$ を決める関数を求めることです。未知関数を $d$ と書き、これを満たす関数方程式を解く問題として定式化すると

$$
\mathcal H(d)=0
$$

と書けます。ここで $\mathcal H$ は関数空間から別の関数空間への作用素です。解析結果には直観を作る、経済メカニズムを理解する、数値近似を検査するという重要な役割があります。その一方で、DSGEモデルが答えようとする多くの問いには数値的方法でしか得られない定量的な答えが必要となります。たとえば、負の供給ショックに対して金融当局が名目金利を下げるべきだと言うだけでは不十分です。政策助言としては、どの程度下げるのか、どれく
らいの期間下げるのかを測る必要があります。したがって、解析的議論がdirection of effectを与えるのに対し、数値解法はmagnitude and duration of effectを与えます。

数値解法は、景気循環分析·政策分析·予測に必要な豊かなDSGEモデルを扱うことを可能にし、推定法はそれらのモデルを厳密にデータへ接続することを可能にします。DSGEモデルの解法と推定法は、GDP、雇用、インフレーション、金利などの集計変数の振る舞いを理解するための二本柱となります。

一般枠組みでは、多くのマクロ経済問題は関数方程式として書くことが可能です。未知の対象は、価値関数、政策関数、Euler方程式を満たす意思決定ルール、条件付き期待などです。状態空間を $\Omega \subset \mathbb R^n$, 未知関数を $d: \Omega \rightarrow \mathbb R^m$, 関数空間を $J_1, J_2$, $\mathcal H: J_1 \rightarrow J_2$ を作用素として関数方程式を

$$
\mathcal H(d)=0
$$

と書けます。たとえば、状態変数を