---
title: Pinocchio
engine: julia
format:
  html:
    code-tools: true
---

::: {.callout-important}
All rights reserved. All errors in this document are the responsibility of the author. 
Although every effort has been made to ensure the accuracy of this material, I cannot guarantee that it is free of errors or misprints. 
Use at your own risk. 
If you find any errors, please get in touch with me.
This note is based on the author's notes for the Stochastic Processes course taught by Professor Katsushi Fukuyama at the Graduate School of Science, Kobe University, during the Fall 2024 semester, and on Nancy L. Stokey's book [*The Economics of Inaction*](https://press.princeton.edu/books/hardcover/9780691135052/the-economics-of-inaction?srsltid=AfmBOoo7_ojSxnPQ7J1z8giWXXzZXAjHyjDy8EL8WR_QwSzbXwLG0aNK) published by Princeton University Press in 2009.
:::

# Notation

Let $\mathcal F$ be a complete $\sigma$-algebra on $\Omega$, and let $P$ be a probability measure on $(\Omega, \mathcal F)$. We shall henceforth work within the probability space $(\Omega, \mathcal F, P)$. A function $X$ on $\Omega$ that is $\mathcal F$-measurable is defined as a random variable. The $\sigma$-algebra generated by the random variables $X_{1}, \dots, X_{n}$ is denoted by $\sigma(X_{1}, \dots, X_{n})$. The expectation of a random variable $X$ is denoted by $\mathbb{E} [X]$ and $\mathbb{E}(X:A) = \mathbb{E} [X \mathbb{1}_{A}] = \int_{A}X(\omega)P(d\omega)$.

# Brownian Motions

